CREATE TABLE clients (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    nickname VARCHAR(255),
    phone VARCHAR(50) NOT NULL,
    alternate_phone VARCHAR(50),
    email VARCHAR(255),
    instagram_handle VARCHAR(255),
    address TEXT,
    city VARCHAR(255),
    province VARCHAR(255),
    postal_code VARCHAR(20),
    country VARCHAR(100) DEFAULT 'Indonesia',
    denomination VARCHAR(255),
    patron_saint_preference VARCHAR(255),
    parish_name VARCHAR(255),
    first_order_date TIMESTAMPTZ,
    total_orders INT DEFAULT 0,
    preferred_payment_method VARCHAR(100),
    notes TEXT,
    status VARCHAR(50) DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT now(),
    created_username VARCHAR(255),
    updated_at TIMESTAMPTZ DEFAULT now(),
    updated_username VARCHAR(255)
);